//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idea.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Idea.Business.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Points.
        /// </summary>
        internal static string ActionPointsHeader {
            get {
                return ResourceManager.GetString("ActionPointsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Collection and Analysis methodologies:.
        /// </summary>
        internal static string DataCollectionHeader {
            get {
                return ResourceManager.GetString("DataCollectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empirical cases and interrelated factors:.
        /// </summary>
        internal static string EmpiricalCasesHeader {
            get {
                return ResourceManager.GetString("EmpiricalCasesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Factors.
        /// </summary>
        internal static string ExternalFactorsHeader {
            get {
                return ResourceManager.GetString("ExternalFactorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Text.
        /// </summary>
        internal static string FullText {
            get {
                return ResourceManager.GetString("FullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Electoral Management and Justice.
        /// </summary>
        internal static string ImprovedElectoralManagementHeader {
            get {
                return ResourceManager.GetString("ImprovedElectoralManagementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Electoral Security.
        /// </summary>
        internal static string ImprovedElectoralSecurityHeader {
            get {
                return ResourceManager.GetString("ImprovedElectoralSecurityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Infrastructure for Peace.
        /// </summary>
        internal static string ImprovedInfrastructurePeaceHeader {
            get {
                return ResourceManager.GetString("ImprovedInfrastructurePeaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Factors.
        /// </summary>
        internal static string InternalFactorsHeader {
            get {
                return ResourceManager.GetString("InternalFactorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction:.
        /// </summary>
        internal static string IntroductionHeader {
            get {
                return ResourceManager.GetString("IntroductionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Resources.
        /// </summary>
        internal static string KnowledgeResourcesHeader {
            get {
                return ResourceManager.GetString("KnowledgeResourcesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observable Indicators:.
        /// </summary>
        internal static string ObservableIndicatorsHeader {
            get {
                return ResourceManager.GetString("ObservableIndicatorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practitioners Tips.
        /// </summary>
        internal static string PractitionersTipsHeader {
            get {
                return ResourceManager.GetString("PractitionersTipsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire:.
        /// </summary>
        internal static string QuestionnaireHeader {
            get {
                return ResourceManager.GetString("QuestionnaireHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
    }
}
