//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idea.Facade.ReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAll", ReplyAction="http://tempuri.org/IReportService/GetAllResponse")]
        System.Collections.Generic.List<Idea.Entities.Report> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAll", ReplyAction="http://tempuri.org/IReportService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Idea.Entities.Report>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/Get", ReplyAction="http://tempuri.org/IReportService/GetResponse")]
        Idea.Entities.Report Get(int idReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/Get", ReplyAction="http://tempuri.org/IReportService/GetResponse")]
        System.Threading.Tasks.Task<Idea.Entities.Report> GetAsync(int idReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetByModel", ReplyAction="http://tempuri.org/IReportService/GetByModelResponse")]
        System.Collections.Generic.List<Idea.Entities.Report> GetByModel(int idModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetByModel", ReplyAction="http://tempuri.org/IReportService/GetByModelResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Idea.Entities.Report>> GetByModelAsync(int idModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/Save", ReplyAction="http://tempuri.org/IReportService/SaveResponse")]
        Idea.Entities.Report Save(Idea.Entities.Report report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/Save", ReplyAction="http://tempuri.org/IReportService/SaveResponse")]
        System.Threading.Tasks.Task<Idea.Entities.Report> SaveAsync(Idea.Entities.Report report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/Delete", ReplyAction="http://tempuri.org/IReportService/DeleteResponse")]
        void Delete(Idea.Entities.Report report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/Delete", ReplyAction="http://tempuri.org/IReportService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(Idea.Entities.Report report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetByName", ReplyAction="http://tempuri.org/IReportService/GetByNameResponse")]
        System.Collections.Generic.List<Idea.Entities.Report> GetByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetByName", ReplyAction="http://tempuri.org/IReportService/GetByNameResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Idea.Entities.Report>> GetByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetByNameAndType", ReplyAction="http://tempuri.org/IReportService/GetByNameAndTypeResponse")]
        System.Collections.Generic.List<Idea.Entities.Report> GetByNameAndType(string name, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetByNameAndType", ReplyAction="http://tempuri.org/IReportService/GetByNameAndTypeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Idea.Entities.Report>> GetByNameAndTypeAsync(string name, int type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : Idea.Facade.ReportService.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<Idea.Facade.ReportService.IReportService>, Idea.Facade.ReportService.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Idea.Entities.Report> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Idea.Entities.Report>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Idea.Entities.Report Get(int idReport) {
            return base.Channel.Get(idReport);
        }
        
        public System.Threading.Tasks.Task<Idea.Entities.Report> GetAsync(int idReport) {
            return base.Channel.GetAsync(idReport);
        }
        
        public System.Collections.Generic.List<Idea.Entities.Report> GetByModel(int idModel) {
            return base.Channel.GetByModel(idModel);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Idea.Entities.Report>> GetByModelAsync(int idModel) {
            return base.Channel.GetByModelAsync(idModel);
        }
        
        public Idea.Entities.Report Save(Idea.Entities.Report report) {
            return base.Channel.Save(report);
        }
        
        public System.Threading.Tasks.Task<Idea.Entities.Report> SaveAsync(Idea.Entities.Report report) {
            return base.Channel.SaveAsync(report);
        }
        
        public void Delete(Idea.Entities.Report report) {
            base.Channel.Delete(report);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(Idea.Entities.Report report) {
            return base.Channel.DeleteAsync(report);
        }
        
        public System.Collections.Generic.List<Idea.Entities.Report> GetByName(string name) {
            return base.Channel.GetByName(name);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Idea.Entities.Report>> GetByNameAsync(string name) {
            return base.Channel.GetByNameAsync(name);
        }
        
        public System.Collections.Generic.List<Idea.Entities.Report> GetByNameAndType(string name, int type) {
            return base.Channel.GetByNameAndType(name, type);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Idea.Entities.Report>> GetByNameAndTypeAsync(string name, int type) {
            return base.Channel.GetByNameAndTypeAsync(name, type);
        }
    }
}
