//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idea.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract]
    [KnownType(typeof(ModelFactor))]
    public partial class Factor
    {
        public Factor()
        {
            this.ModelFactors = new HashSet<ModelFactor>();
    		OnCreated();
        }
    
    	partial void OnCreated();
    
    
    	[DataMember]
        public int IdFactor { get; set; }
    
    	[DataMember]
        public string Name { get; set; }
    
    	[DataMember]
        public string Description { get; set; }
    
    	[DataMember]
        public int ScaleMin { get; set; }
    
    	[DataMember]
        public int ScaleMax { get; set; }
    
    	[DataMember]
        public decimal Interval { get; set; }
    
    	[DataMember]
        public string HtmlDocument { get; set; }
    
    	[DataMember]
        public bool InternalFactor { get; set; }
    
    	[DataMember]
        public bool CumulativeFactor { get; set; }
    
    	[DataMember]
        public string Introduction { get; set; }
    
    	[DataMember]
        public string EmpiricalCases { get; set; }
    
    	[DataMember]
        public string ObservableIndicators { get; set; }
    
    	[DataMember]
        public string DataCollection { get; set; }
    
    	[DataMember]
        public string Questionnaire { get; set; }
    
    	[DataMember]
        public Nullable<int> SortOrder { get; set; }
    
    	[DataMember]
        public string Color { get; set; }
    
    	[DataMember]
        public System.DateTime DateCreated { get; set; }
    
    	[DataMember]
        public System.DateTime DateModified { get; set; }
    
    
    	[DataMember]
        public virtual ICollection<ModelFactor> ModelFactors { get; set; }
    }
}
