//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idea.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract]
    [KnownType(typeof(Marker))]
    public partial class MarkerType
    {
        public MarkerType()
        {
            this.Markers = new HashSet<Marker>();
    		OnCreated();
        }
    
    	partial void OnCreated();
    
    
    	[DataMember]
        public int IDMarkerType { get; set; }
    
    	[DataMember]
        public string Name { get; set; }
    
    	[DataMember]
        public string Symbol { get; set; }
    
    	[DataMember]
        public string Size { get; set; }
    
    	[DataMember]
        public System.DateTime DateCreated { get; set; }
    
    	[DataMember]
        public System.DateTime DateModified { get; set; }
    
    
    	[DataMember]
        public virtual ICollection<Marker> Markers { get; set; }
    }
}
