//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idea.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract]
    [KnownType(typeof(Factor))]
    [KnownType(typeof(Model))]
    [KnownType(typeof(ModelFactorData))]
    public partial class ModelFactor
    {
        public ModelFactor()
        {
            this.ModelFactorDatas = new HashSet<ModelFactorData>();
    		OnCreated();
        }
    
    	partial void OnCreated();
    
    
    	[DataMember]
        public int IDModelFactor { get; set; }
    
    	[DataMember]
        public int IDModel { get; set; }
    
    	[DataMember]
        public int IDFactor { get; set; }
    
    	[DataMember]
        public int ScaleMin { get; set; }
    
    	[DataMember]
        public int ScaleMax { get; set; }
    
    	[DataMember]
        public decimal Interval { get; set; }
    
    	[DataMember]
        public int Weight { get; set; }
    
    	[DataMember]
        public Nullable<int> SortOrder { get; set; }
    
    	[DataMember]
        public System.DateTime DateCreated { get; set; }
    
    	[DataMember]
        public System.DateTime DateModified { get; set; }
    
    
    	[DataMember]
        public virtual Factor Factor { get; set; }
    
    	[DataMember]
        public virtual Model Model { get; set; }
    
    	[DataMember]
        public virtual ICollection<ModelFactorData> ModelFactorDatas { get; set; }
    }
}
