//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idea.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract]
    [KnownType(typeof(Marker))]
    [KnownType(typeof(Region))]
    [KnownType(typeof(ModelFactor))]
    [KnownType(typeof(ModelRiskAlert))]
    [KnownType(typeof(Report))]
    public partial class Model
    {
        public Model()
        {
            this.Markers = new HashSet<Marker>();
            this.ModelFactors = new HashSet<ModelFactor>();
            this.ModelRiskAlerts = new HashSet<ModelRiskAlert>();
            this.Reports = new HashSet<Report>();
    		OnCreated();
        }
    
    	partial void OnCreated();
    
    
    	[DataMember]
        public int IDModel { get; set; }
    
    	[DataMember]
        public int IDRegion { get; set; }
    
    	[DataMember]
        public string Name { get; set; }
    
    	[DataMember]
        public string Description { get; set; }
    
    	[DataMember]
        public System.DateTime DateCreated { get; set; }
    
    	[DataMember]
        public System.DateTime DateModified { get; set; }
    
    
    	[DataMember]
        public virtual ICollection<Marker> Markers { get; set; }
    
    	[DataMember]
        public virtual Region Region { get; set; }
    
    	[DataMember]
        public virtual ICollection<ModelFactor> ModelFactors { get; set; }
    
    	[DataMember]
        public virtual ICollection<ModelRiskAlert> ModelRiskAlerts { get; set; }
    
    	[DataMember]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
