//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idea.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract]
    [KnownType(typeof(Phase))]
    public partial class PhaseBullet
    {
        public PhaseBullet()
        {
    		OnCreated();
        }
    
    	partial void OnCreated();
    
    
    	[DataMember]
        public int IDPhaseBullet { get; set; }
    
    	[DataMember]
        public int IDPhase { get; set; }
    
    	[DataMember]
        public int ColumnNumber { get; set; }
    
    	[DataMember]
        public string Text { get; set; }
    
    	[DataMember]
        public int SortOrder { get; set; }
    
    	[DataMember]
        public System.DateTime DateCreated { get; set; }
    
    	[DataMember]
        public System.DateTime DateModified { get; set; }
    
    
    	[DataMember]
        public virtual Phase Phase { get; set; }
    }
}
