//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idea.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract]
    [KnownType(typeof(Model))]
    [KnownType(typeof(ModelFactorData))]
    [KnownType(typeof(ModelRiskAlertRegion))]
    [KnownType(typeof(Region))]
    [KnownType(typeof(Region))]
    public partial class Region
    {
        public Region()
        {
            this.Models = new HashSet<Model>();
            this.ModelFactorDatas = new HashSet<ModelFactorData>();
            this.ModelRiskAlertRegions = new HashSet<ModelRiskAlertRegion>();
            this.Region1 = new HashSet<Region>();
    		OnCreated();
        }
    
    	partial void OnCreated();
    
    
    	[DataMember]
        public int IDRegion { get; set; }
    
    	[DataMember]
        public string RegionName { get; set; }
    
    	[DataMember]
        public string RegionDescription { get; set; }
    
    	[DataMember]
        public Nullable<int> IDParent { get; set; }
    
    	[DataMember]
        public System.DateTime DateCreated { get; set; }
    
    	[DataMember]
        public System.DateTime DateModified { get; set; }
    
    	[DataMember]
        public string ShapeFileName { get; set; }
    
    	[DataMember]
        public Nullable<int> ShapeFileIndex { get; set; }
    
    	[DataMember]
        public int RegionLevel { get; set; }
    
    	[DataMember]
        public string PathFileName { get; set; }
    
    	[DataMember]
        public string POIFileName { get; set; }
    
    	//[DataMember]
        public virtual ICollection<Model> Models { get; set; }

        //[DataMember]
        public virtual ICollection<ModelFactorData> ModelFactorDatas { get; set; }

        //[DataMember]
        public virtual ICollection<ModelRiskAlertRegion> ModelRiskAlertRegions { get; set; }

        //[DataMember]
        public virtual ICollection<Region> Region1 { get; set; }

        //[DataMember]
        public virtual Region Region2 { get; set; }
    }
}
